// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmyjir6WSnYsGyXO1co_sthXAfiZ-Nks',
    appId: '1:765403769951:web:be765c1ef3ea43d0757fea',
    messagingSenderId: '765403769951',
    projectId: 'geoseize',
    authDomain: 'geoseize.firebaseapp.com',
    storageBucket: 'geoseize.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EFYit5ajR6qirkIV37D-JCCYfgEcMbE',
    appId: '1:765403769951:android:6ec1df66acd0e9ce757fea',
    messagingSenderId: '765403769951',
    projectId: 'geoseize',
    storageBucket: 'geoseize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVCXtJBn2hInd9OLWkDj_7PnHsF706olA',
    appId: '1:765403769951:ios:ae7d1f840c62671a757fea',
    messagingSenderId: '765403769951',
    projectId: 'geoseize',
    storageBucket: 'geoseize.firebasestorage.app',
    iosBundleId: 'com.example.geoseize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVCXtJBn2hInd9OLWkDj_7PnHsF706olA',
    appId: '1:765403769951:ios:ae7d1f840c62671a757fea',
    messagingSenderId: '765403769951',
    projectId: 'geoseize',
    storageBucket: 'geoseize.firebasestorage.app',
    iosBundleId: 'com.example.geoseize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmyjir6WSnYsGyXO1co_sthXAfiZ-Nks',
    appId: '1:765403769951:web:d60549689deab4df757fea',
    messagingSenderId: '765403769951',
    projectId: 'geoseize',
    authDomain: 'geoseize.firebaseapp.com',
    storageBucket: 'geoseize.firebasestorage.app',
  );
}
